// <auto-generated />
using System;
using EstoqueApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstoqueApi.Migrations
{
    [DbContext(typeof(ProdutoContext))]
    [Migration("20211027083403_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("EstoqueApi.Models.Categoria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("EstoqueApi.Models.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("codigo")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("imagem")
                        .HasColumnType("longtext");

                    b.Property<string>("modelo")
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .HasColumnType("longtext");

                    b.Property<double>("preco")
                        .HasColumnType("double");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<string>("tamanho")
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("EstoqueApi.Models.Venda", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ProdutoID")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.Property<double>("data")
                        .HasColumnType("double");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("valorUnitario")
                        .HasColumnType("double");

                    b.HasKey("ID");

                    b.HasIndex("ProdutoID");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("EstoqueApi.Models.Categoria", b =>
                {
                    b.HasOne("EstoqueApi.Models.Produto", "Produto")
                        .WithMany("Categoria")
                        .HasForeignKey("ProdutoID");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EstoqueApi.Models.Venda", b =>
                {
                    b.HasOne("EstoqueApi.Models.Produto", "Produto")
                        .WithMany("Venda")
                        .HasForeignKey("ProdutoID");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("EstoqueApi.Models.Produto", b =>
                {
                    b.Navigation("Categoria");

                    b.Navigation("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
